drop table test_table;
create table test_table (
    EMPNO number,
    ENAME varchar(255),
    JOB varchar(255),
    PROV_EMPLOYEE_EMPNO number,
    PROV_EMPLOYEE_ENAME varchar(255),
    PROV_EMPLOYEE_JOB varchar(255),
    PROV_EMPLOYEE_MGR number,
    PROV_U1__EMPLOYEE_EMPNO number,
    PROV_U1__EMPLOYEE_ENAME varchar(255),
    PROV_U1__EMPLOYEE_JOB varchar(255),
    PROV_U1__EMPLOYEE_MGR number,
    PROV_U1__EMPLOYEE_VERSIONS__#0 number,
    PROV_U2__EMPLOYEE_EMPNO number,
    PROV_U2__EMPLOYEE_ENAME varchar(255),
    PROV_U2__EMPLOYEE_JOB varchar(255),
    PROV_U2__EMPLOYEE_MGR number,
    PROV_U2__EMPLOYEE_VERSIONS__#0 number,
    PROV_U3__EMPLOYEE_EMPNO number,
    PROV_U3__EMPLOYEE_ENAME varchar(255),
    PROV_U3__EMPLOYEE_JOB varchar(255),
    PROV_U3__EMPLOYEE_MGR number,
    PROV_U3__EMPLOYEE_VERSIONS__#0 number,
    PROV_U4__EMPLOYEE_EMPNO number,
    PROV_U4__EMPLOYEE_ENAME varchar(255),
    PROV_U4__EMPLOYEE_JOB varchar(255),
    PROV_U4__EMPLOYEE_MGR number,
    PROV_U4__EMPLOYEE_VERSIONS__#0 number,
    PROV_U5__EMPLOYEE_EMPNO number,
    PROV_U5__EMPLOYEE_ENAME varchar(255),
    PROV_U5__EMPLOYEE_JOB varchar(255),
    PROV_U5__EMPLOYEE_MGR number,
    PROV_U5__EMPLOYEE_VERSIONS__#0 number,
    U1 number,
    U2 number,
    U3 number,
    U4 number,
    U5 number
);
Insert into test_table (EMPNO,ENAME,JOB,PROV_EMPLOYEE_EMPNO,PROV_EMPLOYEE_ENAME,PROV_EMPLOYEE_JOB,PROV_EMPLOYEE_MGR,PROV_U1__EMPLOYEE_EMPNO,PROV_U1__EMPLOYEE_ENAME,PROV_U1__EMPLOYEE_JOB,PROV_U1__EMPLOYEE_MGR,PROV_U1__EMPLOYEE_VERSIONS__#0,PROV_U2__EMPLOYEE_EMPNO,PROV_U2__EMPLOYEE_ENAME,PROV_U2__EMPLOYEE_JOB,PROV_U2__EMPLOYEE_MGR,PROV_U2__EMPLOYEE_VERSIONS__#0,PROV_U3__EMPLOYEE_EMPNO,PROV_U3__EMPLOYEE_ENAME,PROV_U3__EMPLOYEE_JOB,PROV_U3__EMPLOYEE_MGR,PROV_U3__EMPLOYEE_VERSIONS__#0,PROV_U4__EMPLOYEE_EMPNO,PROV_U4__EMPLOYEE_ENAME,PROV_U4__EMPLOYEE_JOB,PROV_U4__EMPLOYEE_MGR,PROV_U4__EMPLOYEE_VERSIONS__#0,PROV_U5__EMPLOYEE_EMPNO,PROV_U5__EMPLOYEE_ENAME,PROV_U5__EMPLOYEE_JOB,PROV_U5__EMPLOYEE_MGR,PROV_U5__EMPLOYEE_VERSIONS__#0, U1, U2, U3, U4, U5) values (678,'King','SA_REP',678,'King','SA_REP',145,666,'King','SA_REP',145,7246690,345,'King','SA_REP',145,7246690,678,'King','SA_REP',145,7246690,678,'King','SA_REP',145,7246690,678,'King','SA_REP',145,7246690, 1, 1, 1, 1, 0);
Insert into test_table (EMPNO,ENAME,JOB,PROV_EMPLOYEE_EMPNO,PROV_EMPLOYEE_ENAME,PROV_EMPLOYEE_JOB,PROV_EMPLOYEE_MGR,PROV_U1__EMPLOYEE_EMPNO,PROV_U1__EMPLOYEE_ENAME,PROV_U1__EMPLOYEE_JOB,PROV_U1__EMPLOYEE_MGR,PROV_U1__EMPLOYEE_VERSIONS__#0,PROV_U2__EMPLOYEE_EMPNO,PROV_U2__EMPLOYEE_ENAME,PROV_U2__EMPLOYEE_JOB,PROV_U2__EMPLOYEE_MGR,PROV_U2__EMPLOYEE_VERSIONS__#0,PROV_U3__EMPLOYEE_EMPNO,PROV_U3__EMPLOYEE_ENAME,PROV_U3__EMPLOYEE_JOB,PROV_U3__EMPLOYEE_MGR,PROV_U3__EMPLOYEE_VERSIONS__#0,PROV_U4__EMPLOYEE_EMPNO,PROV_U4__EMPLOYEE_ENAME,PROV_U4__EMPLOYEE_JOB,PROV_U4__EMPLOYEE_MGR,PROV_U4__EMPLOYEE_VERSIONS__#0,PROV_U5__EMPLOYEE_EMPNO,PROV_U5__EMPLOYEE_ENAME,PROV_U5__EMPLOYEE_JOB,PROV_U5__EMPLOYEE_MGR,PROV_U5__EMPLOYEE_VERSIONS__#0, U1, U2, U3, U4, U5) values (183,'Sewall','MK_MAN',183,'Sewall','MK_MAN',101,183,'Sewall','MK_MAN',101,7246690,183,'Sewall','MK_MAN',101,7246690,183,'Sewall','MK_MAN',101,7246690,183,'Sewall','SA_REP',101,7246690,183,'Sewall','MK_MAN',101,7246690, 0, 0, 0, 1, 1);
commit;
select * from test_table;

